### PR TITLE
Moving objects into scenes

### PR DESCRIPTION
**Pull request by mjkalyan**

### CODE REVIEW

**Comment by mjkalyan** [comment]
The main reason I made some objects outside of `make-scene` (in a `let*`) in shapes example 3 was to reference the previous objects. In the commit message of https://github.com/defun-games/claylib/pull/11/commits/8582e0e4f6f111e029b730535643cfc8ffb85f52 I outline my concern with what I've done here as a workaround.

I think I mentioned it before when talking about improving the scene stuff, but it would be nice if references to earlier bindings were possible in `make-scene`'s asset and object lists. Not really sure how much macro-fu that would take, or if it's feasible at all.

Any thoughts, @shelvick?

**Comment by shelvick** [comment]
Oh, I always have thoughts. They may not be helpful or productive thoughts, but I have them. ;-)

Let's look at some pseudocode that might represent a real-world game:

```
(defvar *assets* (list (make-texture-asset ...) (make-model-asset ...) ...))
(defvar *level-1* (make-scene `((texture-1 ,(car *assets*))
                                (model-1 ,(cadr *assets*))
                                ...)
                              `((platform-1 ,(make-platform ...))
                                (enemy-1 ,(make-enemy ...))
                                ...)))
(defvar *level-2* (make-scene `((texture-1 ,(car *assets*))
                                (model-1 ,(cadr *assets*))
                                ...)
                              `((platform-1 ,(make-platform ...))
                                (enemy-1 ,(make-enemy ...))
                                ...)))

(with-window ()
  (with-scene *level-1* (:free-assets :later)
    (do-game-loop (:end (level-1-completed))
      (level-1-game-logic)
      (with-drawing
        (draw-scene-all))))
  (with-scene *level-2* (:free-assets :later)
    (do-game-loop (:end (level-2-completed))
      (level-2-game-logic)
      (with-drawing
        (draw-scene-all)))))
```

Now you may notice I've taken the liberty to add a few missing features here. But this is a pattern I expect a lot of simpler games will follow -- defining the assets and scenes up front, separating out game logic into functions, freeing objects between scenes but holding onto the assets. Fairly different from the examples we've written up to this point, but we can follow it more closely now that you've done us the amazing favor of package-ifying them all.

Does that address the comment you made in your commit? If `make-scene` is able to reference its own assets and objects, then the issue with freed objects still having references outside of a scene becomes moot, I think.

> I think I mentioned it before when talking about improving the scene stuff, but it would be nice if references to earlier bindings were possible in `make-scene`'s asset and object lists. Not really sure how much macro-fu that would take, or if it's feasible at all.

Not sure off the top of my head the best way to do that, but I'll figure it out. I'm realizing it will be pretty important.

**Comment by mjkalyan** [comment]
> If `make-scene` is able to reference its own assets and objects, then the issue with freed objects still having references outside of a scene becomes moot, I think.

Yeah this makes sense, so in some cases where you might need the same objects in different scenes you could pull the common objects into `*objects*` and use `:free-objects :later`.

> Fairly different from the examples we've written up to this point, but we can follow it more closely now

Okay, I'll follow a similar pattern from now on.

And since my concern is dismissed, this PR should be able to be merged.

**Comment by shelvick** [comment]
Hey, I just got the new version of `make-scene` working. :-) It's a macro now, so the syntax has changed a bit. And yes, getting all the quoting right was fairly painful, but let's not talk about that. See the first texture example.

It did create some conflicts with your latest changes, though. Want to do the honors?

**Comment by mjkalyan** [comment]
That was quick! 

> Want to do the honors?

Sure, I'll do that now.

**Comment by mjkalyan** [comment]
Okay it should be good to go. The new `make-scene` invocations are sleek!

**Comment by mjkalyan** [comment]
I just made the same changes in the existing commits so it's cleaner. Not touching it anymore!

**Pull request merged**
